name: Package Application with Pyinstaller

on: [push, fork, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.6.0

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        spec: main.spec
        requirements: requirements.txt
      
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: csquiz
        path: src/dist/windows
